
alias em='emacsclient -t -a ""'
alias emc='emacsclient -nc -a ""'
EDITOR='emacsclient -a ""'
# C-S for forward-i-search in emacs bash
[[ $- == *i* ]] && stty -ixon

# for find
alias findf="find . -type f | xargs grep -s -R -n " 

# for virtualenv
alias ac="source ./env/bin/activate"
alias de="deactivate"
alias my="mysql.server start"

# for project folder
alias down="cd ~/Downloads"
alias doc="cd ~/Documents"
alias work="cd ~/Workspace"
alias android="cd ~/Workspace/AndroidStudioProjects"
alias oz="cd ~/Workspace/ozsales"
alias per="cd ~/Workspace/persimmon"
alias om="cd ~/Workspace/omnimw"
alias bashconfig="cd ~/bash-config/"
alias aimeipin="cd /Users/Tao/git/aimeipin"
alias sms="cd /Users/Tao/AndroidStudioProjects/SMSRedirector"

# for django
alias djtest="python manage.py test --noinput --nologcapture -s --with-xcoverage --xcoverage-file=$TEST_RESULTS_DIR/coverage.xml --with-xunit --xunit-file=$TEST_RESULTS_DIR/nosetests.xml --cover-package=middleware --cover-branches --cover-erase --exclude-dir=middleware/apps/news/tests --exclude-test=middleware.apps.activities.tests.test_ui.TestActivityUIViewIndex"
alias shell_plus="python manage.py shell_plus"
alias migrate="python manage.py migrate"
alias makemigrations="python manage.py makemigrations"
alias schema="python manage.py schemamigration"
alias code="python manage.py code"
alias manage="python manage.py"

# for ssh
alias pilot="ssh pilot"
alias debian="ssh debian"
alias luotao="ssh luotao"

# for docker
#alias dc="docker"
#alias dcps="docker ps"
#alias dcpl="docker pull"
#alias dcpsa="docker ps -a"
#alias dci="docker images"
#alias dcrm="docker rm"
#alias dcrmi="docker rmi"
#alias dcrun="docker run -it -u='root'"
#alias dcexe="docker exec -it -u='root'"
##alias dcrmx='docker rm $(docker ps -q -f status=exited)'
#alias dcrmx='docker ps -q -f status=exited | xargs docker rm'
#alias dcrmall='docker rm -f $(docker ps -q -a)'
#alias dcstopall='docker stop $(docker ps -q)'
#alias dl='docker ps -l -q'
#alias dcrminone="docker rmi $(docker images | grep "^<none>" | awk -F' ' '{ print $3}')"
#alias dcrmix="docker images | awk '/^<none>/ {print $3}' | xargs docker rmi"

JAVA_HOME=$(/usr/libexec/java_home)
export JAVA_HOME

gittag() {
	if [ -z "$1" ]
		then
	  		echo "Please input tag name."
	  		exit 0
	fi

	TAGNAME=$1
	git tag -d $TAGNAME
	git push origin :refs/tags/$TAGNAME
	git push origin HEAD
	git tag $TAGNAME
	git push origin --tags
}

alias gittag=gittag

